tests

diff --git a/src/bin_stub b/src/bin_stub
--- a/src/bin_stub
+++ b/src/bin_stub
@@ -39,15 +39,18 @@ _bincrypter() {
         _bc_xprintf() { printf "$@"; }
     fi
 
-    _bc_err() { 
+    _bc_err() {
+        echo -e >&2 "${CDR}ERROR${CN}: $*"
         # Be opportunistic: Try to obfuscate but if that fails then just copy data
         # without obfuscation (cat).
         # Consider a system where there is no 'openssl' or 'perl' but the install
         # pipeline looks like this:
         # curl -fL https://foo.com/script | bincrypter -l >script
         # => We rather have a non-obfuscated binary than NONE.
-        [ "$fn" = "-" ] && cat # Pass through
-        echo -e >&2 "${CDR}ERROR${CN}: $*"
+        [ "$fn" = "-" ] && {
+            cat    # Pass through
+            exit 0 # Make pipe succeed
+        }
         exit 255
     }
     # Obfuscate a string with non-printable characters at random intervals.
@@ -154,9 +157,8 @@ _bincrypter() {
         _bcl_verify "$({ fdisk -l | grep -i identifier | head -n1;} 2>/dev/null)" && return
     }
 
-    [ -t 0 ] && [ $# -eq 0 ] && _bc_err "Usage: ${CDC}$0 <file> [<password>]${CN} ${CF}#[use - for stdin]${CN}"
     fn="-"
-    [ -n "$1" ] && fn="$1" # $1 might be '-'
+    [ -n "${1:?}" ] && fn="$1" # $1 might be '-'
     [ "$fn" != "-" ] && [ ! -f "$fn" ] && _bc_err "File not found: $fn"
 
     command -v openssl >/dev/null || _bc_err "openssl is required"
@@ -300,6 +302,7 @@ Encrypt by passing the password as environment variable:
 "
         exit 0
     }
+    [ -t 0 ] && [ $# -eq 0 ] && _bc_usage
     while getopts "hql" opt; do
         case $opt in
             h) _bc_usage ;;
