lock to system

diff --git a/src/bin_stub b/src/bin_stub
--- a/src/bin_stub
+++ b/src/bin_stub
@@ -10,19 +10,24 @@
 #
 # https://github.com/hackerschoice/bincrypter
 
+[ -t 2 ] && {
 CDR="\033[0;31m" # red
 CDG="\033[0;32m" # green
 CDY="\033[0;33m" # yellow
 CDM="\033[0;35m" # magenta
+CM="\033[1;35m" # magenta
 CDC="\033[0;36m" # cyan
 CN="\033[0m"     # none
 CF="\033[2m"     # faint
+}
 
 # %%BEGIN_BC_FUNC%%
-bincrypter() {
+_bincrypter() {
     local str ifn fn s c DATA P _P S HOOK _PASSWORD
     # local DEBUG=1
     local USE_PERL=1
+    local _BC_QUIET="${_OPT_BC_QUIET:-$BC_QUIET}"
+    local _BC_LOCK="${_OPT_BC_LOCK:-$BC_LOCK}"
 
     # vampiredaddy wants this to work if dd + tr are not available:
     if [ -n "$USE_PERL" ]; then
@@ -80,6 +85,65 @@ bincrypter() {
         echo "$str"
     }
 
+    # Sets _P
+    # Return 0 to continue. Otherwise caller should return.
+    # May exit if bin is executed on another host (BC_LOCK).
+    _bcl_gen_p() {
+        local _k
+        # Binary is LOCKED to this host. Check if this is the same host to allow execution.
+        _k="$(_bcl_get)" && _P="$(echo "$1" | openssl enc -d %%SSL_OPTS%% "$_k" -a -A 2>/dev/null)"
+
+        [ -n "$_P" ] && return 0
+        [ -n "$fn" ] && {
+            # sourced
+            unset BCL BCV _P P S fn
+            unset -f _bcl_get _bcl_verify _bcl_verify_dec
+            return 255
+        }
+        # base64 to string
+        BCL="$(echo "$BCL" | openssl base64 -d -A 2>/dev/null)"
+        [ "$BCL" -eq "$BCL" ] 2>/dev/null && exit "$BCL"
+        exec /bin/sh -c "$BCL"
+        exit 255 # FATAL
+    }
+    _bcl_gen() {
+        local _k
+        local p
+        # P:=Encrypt(P) using _bcl_get as key
+        _k="$(_bcl_get)"
+        [ -z "$_k" ] && { echo -e >&2 "${CDR}ERROR${CN}: BC_LOCK not supported on this system"; return 255; }
+        p="$(echo "$P" | openssl enc %%SSL_OPTS%% "${_k}" -a -A 2>/dev/null)"
+        [ -z "$p" ] && { echo -e >&2 "${CDR}ERROR${CN}: Failed to generate BC_LOCK password"; return 255; }
+        P="$p"
+        str+="$(declare -f _bcl_verify_dec)"$'\n'
+        str+="_bcl_verify() { _bcl_verify_dec \"\$@\"; }"$'\n'
+        str+="$(declare -f _bcl_get)"$'\n'
+        str+="$(declare -f _bcl_gen_p)"$'\n'
+        str+="BCL='$(openssl base64 -A <<<"${_BC_LOCK}")'"$'\n'
+        # Add test value
+        str+="BCV='$(echo TEST-VALUE-VERIFY | openssl enc %%SSL_OPTS%% "${_k}" -a -A 2>/dev/null)'"$'\n'
+    }
+    # Test a key candidate and on success output the candidate to STDOUT.
+    _bcl_verify_dec() {
+        [ "TEST-VALUE-VERIFY" != "$(echo "$BCV" | openssl enc -d %%SSL_OPTS%% "${1}-${UID}" -a -A 2>/dev/null)" ] && return 255
+        echo "$1-${UID}"
+    }
+    # Encrypt & Decrypt BCV for testing.
+    _bcl_verify() {
+        # [ "TEST-VALUE-VERIFY" != "$(echo "$BCV" | openssl enc -d %%SSL_OPTS%% "${1}" -a -A 2>/dev/null)" ] && return 255
+        echo "$1-${UID}"
+    }
+    # Generate a LOCK key and output it to STDOUT (if valid).
+    # This script uses the above bcl_verify but the decoder uses its own
+    # bcl_verify as a trampoline to call bcl_verify_dec.
+    # FIXME: Consider cases where machine-id changes. Fallback to dmidecode and others....
+    _bcl_get() {
+        [ -z "$UID" ] && UID="$(id -u 2>/dev/null)"
+        [ -f "/etc/machine-id" ] && _bcl_verify "$(cat "/etc/machine-id")" && return
+        command -v dmidecode >/dev/null && _bcl_verify "$(dmidecode -t 1 2>/dev/null | LANG=C perl -ne '/UUID/ && print')" && return
+        _bcl_verify "$(fdisk -l 2>/dev/null | grep -i identifier 2>/dev/null | head -n1 2>/dev/null)" && return
+    }
+
     command -v openssl >/dev/null || _bc_err "openssl is required"
     fn="-"
     [ -t 0 ] && [ $# -eq 0 ] && _bc_err "Usage: ${CDC}$0 <file> [<password>]${CN} ${CF}#[use - for stdin]${CN}"
@@ -87,7 +151,7 @@ bincrypter() {
     [ "$fn" != "-" ] && [ ! -f "$fn" ] && _bc_err "File not found: $fn"
 
     # Auto-generate password if not provided
-    _PASSWORD="${2:-${BCP:-$PASSWORD}}"
+    _PASSWORD="${2:-${BC_PASSWORD:-$PASSWORD}}"
     [ -z "$_PASSWORD" ] && P="$(DEBUG='' _bc_xdd 32 </dev/urandom | openssl base64 -A | _bc_xtr '^' '[:alnum:]' | DEBUG='' _bc_xdd 16)"
     _P="${_PASSWORD:-$P}"
     [ -z "$_P" ] && _bc_err "No ${CDC}PASSWORD=<password>${CN} provided and failed to generate one."
@@ -96,20 +160,34 @@ bincrypter() {
     # Auto-generate SALT
     S="$(DEBUG='' _bc_xdd 32 </dev/urandom | openssl base64 -A | _bc_xtr '^' '[:alnum:]' | DEBUG='' _bc_xdd 16)"
 
+    # base64 encoded decrypter
     HOOK='%%HOOK%%'
+
+    # _P - used with openssl below
+    #  P - stored in P=$P
     unset str
-    ## Add Password (obfuscated) to script (dangerous: readable)
-    [ -n "$P" ] && str="P=$(echo "$P"|openssl base64 -A 2>/dev/null)"$'\n'
+    [ -n "$_BC_LOCK" ] && _bcl_gen
+    # Fallback
+    [ -z "$str" ] && {
+        str="unset BCV BCL"$'\n'
+        P="$(echo "$P"|openssl base64 -A 2>/dev/null)"
+    }
+
+    ## Add Password to script ($P might be encrypted if BC_LOCK is set)
+    [ -n "$P" ] && {
+        str+="P=${P}"$'\n'
+        unset P
+    }
 
     ## Add SALT to script
     str+="S='$S'"$'\n'"$(echo "$HOOK"|openssl base64 -A -d)"
-    [ -n "$DEBUG" ] && echo >&2 "DEBUG: code='$str'"
+    [ -n "$DEBUG" ] && { echo -en >&2 "DEBUG: ===code===\n${CDM}${CF}"; echo >&2 "$str"; echo -en >&2 "${CN}"; }
 
     ## Encode & obfuscate the HOOK
     HOOK="$(echo "$str" | openssl base64 -A)"
     HOOK="$(_bc_ob64 "$HOOK")"
 
-    [ "$fn" != "-" ] && { 
+    [ -z "$_BC_QUIET" ] && [ "$fn" != "-" ] && { 
         s="$(stat -c %s "$fn")"
         [ "$s" -gt 0 ] || _bc_err "Empty file: $fn"
     }
@@ -151,12 +229,68 @@ bincrypter() {
         c="$(stat -c %s "$fn" 2>/dev/null)"
         [ -n "$c" ] && echo -e >&2 "${CDY}Compressed:${CN} ${CDM}$s ${CF}-->${CN}${CDM} $c ${CN}[${CDG}$((c * 100 / s))%${CN}]"
     }
-    unset -f _bc_err _bc_ob64 _bc_obbell _bc_xdd _bc_xtr _bc_xprintf
+    # [ -z "$_BC_QUIET" ] && [ -n "$_BC_LOCK" ] && echo -e >&2 "${CDY}PASSWORD=${CF}${_P}${CN}"
+    unset -f _bcl_get _bcl_verify _bcl_verify_dec _bc_err _bc_ob64 _bc_obbell _bc_xdd _bc_xtr _bc_xprintf
 }
 # %%END_BC_FUNC%%
 
-# Execute if not sourced:
+# Check if sourced or executed
 [ -n "$ZSH_VERSION" ] && [ "$ZSH_EVAL_CONTEXT" != "${ZSH_EVAL_CONTEXT%":file:"*}" ] && _sourced=1
 (return 0 2>/dev/null) && _sourced=1
-[ -z "$_sourced" ] && bincrypter "$@"
+[ -z "$_sourced" ] && {
+    # Execute if not sourced:
+    _bc_usage() {
+        local bc="${0##*/}"
+        echo -en >&2 "\
+${CM}Encrypt a binary or script.${CDM}
+The password is chosen at random unless specified by the user.
+
+${CDG}Usage:${CN}
+${CDC}${bc} ${CDY}[-hql] [file] [password]${CN}
+   -h   This help
+   -q   Quiet mode (no output)
+   -l   Lock binary to this system & UID or fail if copied.
+        It will exit with BC_LOCK if set to a numerical value.
+        Otherwise it will execute BC_LOCK as a command.
+        The default is to exit with 0 if copied.
+
+${CDG}Environment variables (optional):${CN}
+${CDY}PASSWORD=${CN}     Password to encrypt/decrypt.
+${CDY}BC_PASSWORD=${CN}  Password to encrypt/decrypt (exported).
+${CDY}BC_QUIET=${CN}     See -q
+${CDY}BC_LOCK=${CN}      See -l
+
+${CDG}Examples:${CN}
+Encrypt myfile.sh with a random password:
+  ${CDC}${bc} ${CDY}myfile.sh${CN}
+
+Encrypt myfile.sh with password 'mysecret':
+  ${CDC}${bc} ${CDY}myfile.sh ${CDY}mysecret${CN}
+
+Encrypt by passing the password as environment variable:
+  ${CDY}PASSWORD=mysecret ${CDC}${bc} ${CDY}myfile.sh${CN}
+
+Encrypt /usr/bin/id with a random password:
+  ${CDC}cat ${CDY}/usr/bin/id${CN} | ${CDC}${bc}${CN} >${CDY}id.enc${CN}
+
+Lock to system. Execute 'id; ls -al' if copied:
+  ${CDY}BC_LOCK='id; ls -al' ${CDC}${bc} ${CDY}myfile.sh${CN}
+
+"
+        exit 0
+    }
+    while getopts "hql" opt; do
+        case $opt in
+            h) _bc_usage ;;
+            q) _OPT_BC_QUIET=1 ;;
+            l) _OPT_BC_LOCK=0 ;;
+            *) ;;
+        esac
+    done
+    shift $((OPTIND - 1))
+
+    _bincrypter "$@"
+}
+
+### HERE: sourced
 unset _sourced
