tests

diff --git a/src/bin_stub b/src/bin_stub
--- a/src/bin_stub
+++ b/src/bin_stub
@@ -24,7 +24,6 @@ CF="\033[2m"     # faint
 # %%BEGIN_BC_FUNC%%
 _bincrypter() {
     local str ifn fn s c DATA P _P S HOOK _PASSWORD
-    # local DEBUG=1
     local USE_PERL=1
     local _BC_QUIET="${_OPT_BC_QUIET:-$BC_QUIET}"
     local _BC_LOCK="${_OPT_BC_LOCK:-$BC_LOCK}"
@@ -40,7 +39,17 @@ _bincrypter() {
         _bc_xprintf() { printf "$@"; }
     fi
 
-    _bc_err() { echo -e >&2 "${CDR}ERROR${CN}: $*"; exit 255; }
+    _bc_err() { 
+        # Be opportunistic: Try to obfuscate but if that fails then just copy data
+        # without obfuscation (cat).
+        # Consider a system where there is no 'openssl' or 'perl' but the install
+        # pipeline looks like this:
+        # curl -fL https://foo.com/script | bincrypter -l >script
+        # => We rather have a non-obfuscated binary than NONE.
+        [ "$fn" = "-" ] && cat # Pass through
+        echo -e >&2 "${CDR}ERROR${CN}: $*"
+        exit 255
+    }
     # Obfuscate a string with non-printable characters at random intervals.
     # Input must not contain \ (or sh gets confused)
     _bc_ob64() {
@@ -145,11 +154,14 @@ _bincrypter() {
         _bcl_verify "$({ fdisk -l | grep -i identifier | head -n1;} 2>/dev/null)" && return
     }
 
-    command -v openssl >/dev/null || _bc_err "openssl is required"
-    fn="-"
     [ -t 0 ] && [ $# -eq 0 ] && _bc_err "Usage: ${CDC}$0 <file> [<password>]${CN} ${CF}#[use - for stdin]${CN}"
-    [ -n "$1" ] && fn="$1"
+    fn="-"
+    [ -n "$1" ] && fn="$1" # $1 might be '-'
     [ "$fn" != "-" ] && [ ! -f "$fn" ] && _bc_err "File not found: $fn"
+
+    command -v openssl >/dev/null || _bc_err "openssl is required"
+    command -v perl >/dev/null || _bc_err "perl is required"
+    [ ! -c "/dev/urandom" ] && _bc_err "/dev/urandom is required"
 
     # Auto-generate password if not provided
     _PASSWORD="${2:-${BC_PASSWORD:-$PASSWORD}}"
@@ -182,9 +194,23 @@ _bincrypter() {
     }
 
     ## Add SALT to script
-    str+="S='$S'"$'\n'"$(echo "$HOOK"|openssl base64 -A -d)"
-    [ -n "$DEBUG" ] && { echo -en >&2 "DEBUG: ===code===\n${CDM}${CF}"; echo >&2 "$str"; echo -en >&2 "${CN}"; }
+    str+="S='$S'"$'\n'
 
+    # Bash strings are not binary safe. Instead, store the binary as base64 in memory:
+    ifn="$fn"
+    [ "$fn" = "-" ] && ifn="/dev/stdin"
+    DATA="$(gzip <"$ifn" | openssl base64)" || exit
+
+    ## Add size of random padding to script (up to roughly 25% of the file size)).
+    [ "$BC_PADDING" != "0" ] && {
+        local sz="${#DATA}"
+        [ "$sz" -lt 31337 ] && sz=31337
+        local R="$(( (RANDOM * 32768 + RANDOM) % ((sz / 100) * ${BC_PADDING:-25})))"
+    }
+    str+="R=${R:-0}"$'\n'
+
+    str+="$(echo "$HOOK"|openssl base64 -A -d)"
+    [ -n "$DEBUG" ] && { echo -en >&2 "DEBUG: ===code===\n${CDM}${CF}"; echo >&2 "$str"; echo -en >&2 "${CN}"; }
     ## Encode & obfuscate the HOOK
     HOOK="$(echo "$str" | openssl base64 -A)"
     HOOK="$(_bc_ob64 "$HOOK")"
@@ -193,10 +219,6 @@ _bincrypter() {
         s="$(stat -c %s "$fn")"
         [ "$s" -gt 0 ] || _bc_err "Empty file: $fn"
     }
-    # Bash strings are not binary safe. Instead, store the binary as base64 in memory:
-    ifn="$fn"
-    [ "$fn" = "-" ] && ifn="/dev/stdin"
-    DATA="$(openssl base64 <"$ifn")" || exit
 
     [ "$fn" = "-" ] && fn="/dev/stdout"
 
@@ -221,10 +243,8 @@ _bincrypter() {
         ## Add my hook to decrypt/execute binary
         # echo "eval \"\$(echo $HOOK|strings -n1|openssl base64 -d)\""
         echo "$(_bc_obbell 'eval "')\$$(_bc_obbell '(echo ')$HOOK|{ LANG=C $(_bc_obbell "perl -pe \"s/[^[:print:]]//g\"");}$(_bc_obbell "|openssl base64 -A -d)")\""
-        # Note: openssl expects \n at the end. Perl filters it. Add it with echo.
-        # echo "$(_bc_obbell 'eval "')\$$(_bc_obbell '(echo ')$HOOK|{ LANG=C $(_bc_obbell "perl -pe \"s/[^[:print:]]//g\";echo");}$(_bc_obbell "|openssl base64 -A -d)")\""
         # Add the encrypted binary (from memory)
-        openssl base64 -d<<<"$DATA" |gzip|openssl enc %%SSL_OPTS%% "${S}-${_P}" 2>/dev/null
+        ( DEBUG='' _bc_xdd "$R" </dev/urandom; openssl base64 -d<<<"$DATA") |openssl enc %%SSL_OPTS%% "${S}-${_P}" 2>/dev/null
     } > "$fn"
 
     [ -n "$s" ] && {
@@ -258,6 +278,7 @@ ${CDC}${bc} ${CDY}[-hql] [file] [password]${CN}
 ${CDG}Environment variables (optional):${CN}
 ${CDY}PASSWORD=${CN}     Password to encrypt/decrypt.
 ${CDY}BC_PASSWORD=${CN}  Password to encrypt/decrypt (exported to callee).
+${CDY}BC_PADDING=n${CN}  Add 0..n% of random data to the binary [default: 25].
 ${CDY}BC_QUIET=${CN}     See -q
 ${CDY}BC_LOCK=${CN}      See -l
 
